#!/bin/sh
# https://askubuntu.com/a/1063529
export id=`xinput list | grep -i touchpad | awk -F"=" '{ print $2 }' | awk '{ print $1 }'`
xinput list-props "${id}" | grep "Synaptics Scrolling Distance" | sed 's/[^0-9 \t-]//g' | while read a b c;
do
 echo "${a} ${b} $((${c}*-1))";
 xinput set-prop "${id}" "${a}" "${b}" "$((${c}*-1))"
done
