#!/bin/bash

# neovim
sudo apt install -y neovim

# exFAT for my exteral SSD
sudo add-apt-repository universe
sudo apt update
sudo apt install -y exfat-fuse exfat-utils

# TLP for power management
sudo add-apt-repository ppa:linrunner/tlp
sudo apt-get update
sudo apt-get install -y tlp tlp-rdw

# thermald
sudo apt-get install -y thermald

# psensor
sudo apt-get install -y lm-sensors hddtemp
sudo sensors-detect
sudo apt install -y psensor

# zsh, ohmyzsh
sudo apt install -y zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

